name: BrowserStack Tests
on: [push, pull_request]
jobs:
  buid:
    name: 'inji-web-test'
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      
    steps:
      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'BrowserStack Local Tunnel Setup'  # Invokes the setup-local action
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: Replace BrowserStack credentials in browserstack.yml
        run: |
          cd inji-web-test
          sed -i "s/userName:.*/username: $BROWSERSTACK_USERNAME/g" browserstack.yml
          sed -i "s/accessKey:.*/accessKey: $BROWSERSTACK_USERNAME/g" browserstack.yml
          cat browserstack.yml

      - name: 'Run tests'
        run: |
          cd inji-web-test
          mvn clean test  -DtestngXmlFile="TestNg.xml"

      - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
